plugins {
    id 'java-library'
    id 'org.springframework.boot' apply false
    id 'io.spring.dependency-management'
}

group = 'io.bitnomio'
version = '0.0.1-SNAPSHOT'

dependencies {
    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

jar {
    enabled = true
}

test {
    useJUnitPlatform()
}
