plugins {
    id 'java-library'
    id 'org.springframework.boot' apply false
    id 'io.spring.dependency-management'
}

group = 'com.company'
version = '0.0.1-SNAPSHOT'
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    // Spring Boot Core
    api 'org.springframework.boot:spring-boot-starter'
    
    // Common Domain
    api project(':services:libs:common-domain')
    
    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

//bootJar {
//    enabled = false
//}

jar {
    enabled = true
}

test {
    useJUnitPlatform()
}