# Micronaut Server Configuration
micronaut.server.port=${SERVER_PORT:8020}
micronaut.caches.discovery-client.enabled=false

# Logging Configuration
# Metrics
micronaut.metrics.enabled=true
micronaut.metrics.sensitive=false
micronaut.metrics.binders.files.enabled=true
micronaut.metrics.binders.jdbc.enabled=true
micronaut.metrics.binders.jvm.enabled=true
micronaut.metrics.binders.logback.enabled=true
micronaut.metrics.binders.processor.enabled=true
micronaut.metrics.binders.uptime.enabled=true
micronaut.metrics.binders.web.enabled=true

# CloudWatch Metrics Exporter
micronaut.metrics.export.cloudwatch.namespace=auth-service
micronaut.metrics.export.cloudwatch.enabled=true

# Database and Persistence Configuration
## Flyway Configuration for Database Migration
flyway.datasources.default.enabled=true
flyway.datasources.default.locations[0]=classpath:/db/migrations
flyway.datasources.default.schemas=public.${DB_DATABASE_NAME:`users`}
flyway.datasources.default.baseline-on-migrate=true
flyway.datasources.default.baseline-description=Init schema configuration
flyway.datasources.default.baseline-version=1
flyway.datasources.default.table=migration_history
flyway.datasources.default.connect-retries=3
flyway.datasources.default.connect-retries-interval=5

## Database Connection Configuration
### Read Datasource
datasources.default.db-type=postgres
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES
datasources.default.url=${DB_HOSTNAME:`jdbc:postgresql://localhost:5432/users`}
datasources.default.username=${DB_USERNAME:`bitnomio`}
datasources.default.password=${DB_PASSWORD:`secret`}
datasources.default.schema=public
datasources.default.schema-generate=NONE
datasources.default.minPoolSize=1
datasources.default.maxPoolSize=8

### Write Datasource
datasources.write-ds.db-type=postgres
datasources.write-ds.driver-class-name=org.postgresql.Driver
datasources.write-ds.dialect=POSTGRES
datasources.write-ds.url=${DB_HOSTNAME:`jdbc:postgresql://localhost:5432/users`}
datasources.write-ds.username=${DB_USERNAME:`bitnomio`}
datasources.write-ds.password=${DB_PASSWORD:`secret`}
datasources.write-ds.schema-generate=NONE
datasources.write-ds.schema=public
datasources.write-ds.minPoolSize=1
datasources.write-ds.maxPoolSize=8



## Transaction Manager Configuration
micronaut.data.transaction-manager=jdbc-default
micronaut.data.jdbc.default.dialect=POSTGRES

# JWT Security Configuration
micronaut.security.token.jwt.enabled=false
micronaut.security.token.generator.access-token.expiration=3600
micronaut.security.token.jwt.signatures.secret.generator.secret=${SUPERADMIN_JWT_SECRET}
micronaut.security.token.jwt.signatures.secret.generator.base64=false
micronaut.security.token.jwt.signatures.secret.generator.jws-algorithm=HS256
micronaut.security.token.jwt.generator.refresh-token.base64=false
micronaut.security.token.jwt.generator.refresh-token.enabled=false
micronaut.security.token.jwt.generator.refresh-token.secret=${JWT_SECRET_INTERNAL_API}
micronaut.security.token.jwt.generator.secret.generator.jws-algorithm=HS256

# Redis Configuration
redis.uri=${STAGING_REDIS_PLUTUS:`redis://localhost:6379`}

app.version=1.0.0
app.type=service
app.locale=${APP_LOCALE:`es-ES`}
